version: '{build}'

skip_tags: true

image:
  - Visual Studio 2022
  - Ubuntu

build_script:
- pwsh: ./Build.ps1

test: off

artifacts:
- path: artifacts/Serilog.*.nupkg
- path: artifacts/Serilog.*.snupkg

for:
-
  matrix:
    only:
      - image: Visual Studio
  deploy:
  - provider: NuGet
    api_key:
      secure: 60gpLnipFCiKLpS7ECI1C6EPJW27KzVwqrBVkEzX6FIMTmsG//HD3p8Oq7WdQPm8
    on:
      branch: /^(main|dev)$/
  - provider: GitHub
    auth_token:
      secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
    artifacts:
      /Serilog.*\.nupkg/
      /Serilog.*\.snupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: main
